version: '3'

services:
  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    networks:
      - clinica-network
    depends_on:
      - fastapi

  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    networks:
      - clinica-network

networks:
  clinica-network:
    driver: bridge
